### ISSUE TITLE
SetSSID seems to race the async event polling

### ISSUE THREAD

**Issue by csweichel** [soypat/cyw43439#36]
Thank you for all the hard work you put into this library. Using it, and getting started with it, was super straight forward and a pleasure 🙇.

When I attempt to join my WiFi network I noticed that the [`setSSID` call](https://github.com/soypat/cyw43439/blob/06c7a8266e22193d0395ca89ec4e48f8462ad377/wifi.go#L158) seemed to race the subsequent async status poll. Join events would repeatedly fail in [`state`](https://github.com/soypat/cyw43439/blob/06c7a8266e22193d0395ca89ec4e48f8462ad377/wifi.go#L173) `linkStateUpWaitForSSID`.

As a test/hack/workaround: adding a 100ms delay [after the `setSSID` call](https://github.com/soypat/cyw43439/blob/06c7a8266e22193d0395ca89ec4e48f8462ad377/wifi.go#L162) made the WiFi join work reliably.

**Comment by soypat** [comment]
@csweichel Thanks for your kind words <3

> [setSSID call](https://github.com/soypat/cyw43439/blob/06c7a8266e22193d0395ca89ec4e48f8462ad377/wifi.go#L158) seemed to race the subsequent async status poll.

Hmm, not sure I understand- setSSID blocks until all I/O completes†, and the lock to the device is held the whole time by JoinWPA2 , so there's no competing goroutine access as far as I can tell.

That said- now you do mention it I do see a race happening between the call to [`doIoctlSet` inside `setSSID`](https://github.com/soypat/cyw43439/blob/06c7a8266e22193d0395ca89ec4e48f8462ad377/wifi.go#L244) and the subsequent setting of the [`state` field](https://github.com/soypat/cyw43439/blob/06c7a8266e22193d0395ca89ec4e48f8462ad377/wifi.go#L165) since ioctl methods will process any packet received [inside of `rx`](https://github.com/soypat/cyw43439/blob/06c7a8266e22193d0395ca89ec4e48f8462ad377/ioctl.go#L455-L461), including [Events that may modify `state`](https://github.com/soypat/cyw43439/blob/06c7a8266e22193d0395ca89ec4e48f8462ad377/ioctl.go#L529-L552).

If this is a true race then I'd imagine a possible fix to this would be setting the `state` field within `setSSID` right before `doIoctlSet` is aclled, since `setSSID` starts the connection process anyways. 

† Note: In latest `main` branch.

**Comment by soypat** [comment]
@csweichel I've managed to replicate this behaviour and tested out your fix and had good results. Thank you for your suggestions! Are you able to test #38 ?

**Comment by soypat** [comment]
@csweichel I'll keep this one open for a week before closing as it seems your suggestions yielded great results in PR #38.
