### ISSUE TITLE
module: can minimum version be lower?

### ISSUE THREAD

**Issue by deadprogram** [soypat/cyw43439#48]
Just wonder if it would be possible to set an older version of Go as the minimum for this package by setting something different in the `go.mod` file?

https://github.com/soypat/cyw43439/blob/main/go.mod#L3

The `pio` package minimum is Go 1.19 for example.

https://github.com/tinygo-org/pio/blob/main/go.mod#L3

The reason I am asking for this is because the bluetooth package minimum is Go 1.18

https://github.com/tinygo-org/bluetooth/blob/release/go.mod#L3

**Comment by soypat** [comment]
The version can be lowered to 1.20 without breaking anything. The issue with going lower lies with the use of `unsafe.StringData` [here](https://github.com/soypat/cyw43439/blob/2db714bca0d6e5fcb5c966a40721d2523e1b16ae/bus.go#L310). I'm not entirely sure, but if I recall correctly usage of unsafe.StringData is required since TinyGo handles string headers differently from native Go. It was quite a headache to get that compiling with both upstream Go and tinygo before unsafe.StringData.

**Comment by soypat** [comment]
I've bumped the Go version down in bluetooth development. Does that help?

**Comment by deadprogram** [comment]
Yes, thank you! Now closing.
